/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author luzne
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        
        cerrar();
        this.setLocationRelativeTo(null);
    }
    
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter()
            {
            public void windowClosing(WindowEvent e){
                confirmarsalida();
}
            });
        }catch(Exception e){

}
    }
    public void confirmarsalida(){
        int valor=JOptionPane.showConfirmDialog
          (this,"¿Desea cerrar la aplicación?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(valor==JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null,"Hasta pronto","",JOptionPane.INFORMATION_MESSAGE);
                System.exit(0);
            }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnAlumnos = new javax.swing.JButton();
        btnGestion_Alum = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(28, 50, 96));
        jLabel3.setText("Principal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 50));

        btnAlumnos.setBackground(new java.awt.Color(28, 50, 96));
        btnAlumnos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        btnAlumnos.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Escuela\\src\\main\\java\\imagenes\\alum.png")); // NOI18N
        btnAlumnos.setText("Alumnos");
        btnAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 210, 70));

        btnGestion_Alum.setBackground(new java.awt.Color(28, 50, 96));
        btnGestion_Alum.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnGestion_Alum.setForeground(new java.awt.Color(255, 255, 255));
        btnGestion_Alum.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Escuela\\src\\main\\java\\imagenes\\g_alum.png")); // NOI18N
        btnGestion_Alum.setText("Horarios");
        btnGestion_Alum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGestion_Alum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestion_AlumActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestion_Alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 280, -1));

        btnCurso.setBackground(new java.awt.Color(28, 50, 96));
        btnCurso.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnCurso.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Escuela\\src\\main\\java\\imagenes\\curs.png")); // NOI18N
        btnCurso.setText("Cursos");
        btnCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 210, 70));

        btnCalificaciones.setBackground(new java.awt.Color(28, 50, 96));
        btnCalificaciones.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btnCalificaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnCalificaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Escuela\\src\\main\\java\\imagenes\\cali.png")); // NOI18N
        btnCalificaciones.setText("Calificaciones");
        btnCalificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 280, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\luzne\\OneDrive\\Documentos\\NetBeansProjects\\Escuela\\src\\main\\java\\imagenes\\prin.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
     Registrar_alum registrar_alum=new Registrar_alum();
     registrar_alum.setVisible(true);
     dispose();
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
     Registrar_calificaciones registrar_calificaciones=new Registrar_calificaciones();
     registrar_calificaciones.setVisible(true);
     dispose();
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    private void btnGestion_AlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestion_AlumActionPerformed
                                     
    Horario horario=new Horario();
     horario.setVisible(true);
     dispose();
    }//GEN-LAST:event_btnGestion_AlumActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
       Registro_curso registro_curso=new Registro_curso();
     registro_curso.setVisible(true);
     dispose();
    }//GEN-LAST:event_btnCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnCalificaciones;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnGestion_Alum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
